[package]
name = "any_generics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nutype = { path = "../../nutype", features = ["serde"] }
serde = "1.0.203"
serde_json = "1.0.117"
